let a = [
  {
    address_id: 78021669,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-16T00:44:43",
    customer_id: 72567040,
    email: "evanlyons21@yahoo.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 182370346,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-30T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-16T00:44:46",
    variant_title: "",
  },
  {
    address_id: 78008585,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-15T21:03:46",
    customer_id: 72555460,
    email: "jon.bynoe@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 182331858,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-29T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-15T21:06:30",
    variant_title: "",
  },
  {
    address_id: 77946176,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-15T13:01:42",
    customer_id: 72501011,
    email: "jupenningt2@msn.co",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 182200942,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-29T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-15T13:01:46",
    variant_title: "",
  },
  {
    address_id: 77836430,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-13T19:32:08",
    customer_id: 72402791,
    email: "ndschex79@hotmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 181824774,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-27T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-13T19:32:11",
    variant_title: "",
  },
  {
    address_id: 77778323,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: "This is too expensive",
    cancellation_reason_comments: "",
    cancelled_at: "2021-09-13T11:02:43",
    charge_interval_frequency: "3",
    created_at: "2021-09-12T22:55:01",
    customer_id: 72350589,
    email: "lcurt2@uis.edu",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 0,
    id: 181652064,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: null,
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "CANCELLED",
    updated_at: "2021-09-13T11:02:43",
    variant_title: "",
  },
  {
    address_id: 77777517,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-12T22:35:54",
    customer_id: 72349828,
    email: "natalie.e.biondi@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 181649366,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-26T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-12T22:35:57",
    variant_title: "",
  },
  {
    address_id: 77771605,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-12T20:36:49",
    customer_id: 72344535,
    email: "cooperblythe@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 181625646,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-26T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-12T20:36:52",
    variant_title: "",
  },
  {
    address_id: 77714725,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-11T18:44:07",
    customer_id: 72292348,
    email: "teachercamp@hotmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 181420375,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-25T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-11T18:44:11",
    variant_title: "",
  },
  {
    address_id: 77709604,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-11T16:40:10",
    customer_id: 72287578,
    email: "decarrera99@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 181402964,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-25T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-11T16:40:14",
    variant_title: "",
  },
  {
    address_id: 77704321,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-11T14:42:19",
    customer_id: 72282805,
    email: "mishkamaks@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 181385081,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-25T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-11T14:42:21",
    variant_title: "",
  },
  {
    address_id: 77653643,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-10T14:57:16",
    customer_id: 72236498,
    email: "inklingthoughts592@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 181203965,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-24T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-10T14:57:19",
    variant_title: "",
  },
  {
    address_id: 77565390,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-09T03:02:15",
    customer_id: 72158786,
    email: "barryphillips@westnet.com.au",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 180903209,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-23T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-09T03:02:18",
    variant_title: "",
  },
  {
    address_id: 77556528,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-08T21:51:03",
    customer_id: 72150461,
    email: "eugenemartinez4153@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 180866004,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-22T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-08T21:51:06",
    variant_title: "",
  },
  {
    address_id: 77547309,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-08T18:23:49",
    customer_id: 72142116,
    email: "haysu@outlook.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 180820843,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-22T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-08T18:23:52",
    variant_title: "",
  },
  {
    address_id: 77169051,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-04T13:25:38",
    customer_id: 71823439,
    email: "chgomckenzies@sbcglobal.net",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 179742035,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-18T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-04T13:25:40",
    variant_title: "",
  },
  {
    address_id: 77154999,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-09-04T09:13:46",
    customer_id: 71823439,
    email: "chgomckenzies@sbcglobal.net",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 179695202,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-09-18T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-04T09:13:49",
    variant_title: "",
  },
  {
    address_id: 77112783,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: "This was created by accident",
    cancellation_reason_comments: "",
    cancelled_at: "2021-09-14T23:21:25",
    charge_interval_frequency: "3",
    created_at: "2021-09-03T13:30:59",
    customer_id: 71785810,
    email: "miracle819@yahoo.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 0,
    id: 179549491,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: null,
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "CANCELLED",
    updated_at: "2021-09-14T23:21:24",
    variant_title: "",
  },
  {
    address_id: 77077568,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: "Other reason",
    cancellation_reason_comments: "",
    cancelled_at: "2021-09-07T13:57:49",
    charge_interval_frequency: "3",
    created_at: "2021-09-02T21:38:09",
    customer_id: 71754558,
    email: "katierkuehl@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 0,
    id: 179429911,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: null,
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "CANCELLED",
    updated_at: "2021-09-07T13:57:48",
    variant_title: "",
  },
  {
    address_id: 77023890,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: "I already have more than I need",
    cancellation_reason_comments: null,
    cancelled_at: "2021-09-07T21:21:46",
    charge_interval_frequency: "3",
    created_at: "2021-09-02T08:02:40",
    customer_id: 71709110,
    email: "kaibilotta@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 0,
    id: 179265003,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: null,
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "CANCELLED",
    updated_at: "2021-09-07T21:21:46",
    variant_title: "",
  },
  {
    address_id: 76945290,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "6",
    created_at: "2021-09-01T07:43:54",
    customer_id: 71647263,
    email: "kl.solomon@att.net",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 179019004,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-12-15T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "6",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-12T22:33:19",
    variant_title: "",
  },
  {
    address_id: 76926798,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "6",
    created_at: "2021-08-31T21:17:04",
    customer_id: 71630423,
    email: "kej868@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 178944481,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2022-03-14T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "6",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-09-11T20:57:07",
    variant_title: "",
  },
  {
    address_id: 76846782,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-08-30T19:16:59",
    customer_id: 71558873,
    email: "victorsalas0217@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 0,
    id: 178681339,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: null,
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-08-30T19:17:02",
    variant_title: "",
  },
  {
    address_id: 76664695,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: "I already have more than I need",
    cancellation_reason_comments: null,
    cancelled_at: "2021-09-09T22:24:48",
    charge_interval_frequency: "3",
    created_at: "2021-08-28T18:40:46",
    customer_id: 71400645,
    email: "gbrink@cass.net",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 0,
    id: 178106185,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: null,
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "CANCELLED",
    updated_at: "2021-09-09T22:24:48",
    variant_title: "",
  },
  {
    address_id: 76638505,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-08-28T10:09:02",
    customer_id: 71376896,
    email: "eric.l.sparks@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 178019263,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-12-11T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-08-28T10:09:07",
    variant_title: "",
  },
  {
    address_id: 76637049,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: "I already have more than I need",
    cancellation_reason_comments: null,
    cancelled_at: "2021-09-08T12:06:32",
    charge_interval_frequency: "3",
    created_at: "2021-08-28T09:39:07",
    customer_id: 71375570,
    email: "suzannaziko12@gmail.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 0,
    id: 178014249,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: null,
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "CANCELLED",
    updated_at: "2021-09-08T12:06:32",
    variant_title: "",
  },
  {
    address_id: 76633512,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-08-28T08:10:12",
    customer_id: 71372371,
    email: "Newman.john@athenamfg.com",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 178000956,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-12-11T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-08-28T08:10:14",
    variant_title: "",
  },
  {
    address_id: 76588002,
    analytics_data: {
      utm_params: [],
    },
    cancellation_reason: null,
    cancellation_reason_comments: null,
    cancelled_at: null,
    charge_interval_frequency: "3",
    created_at: "2021-08-27T12:32:16",
    customer_id: 71330988,
    email: "as@faithassembly.org",
    expire_after_specific_number_of_charges: null,
    has_queued_charges: 1,
    id: 177851021,
    is_prepaid: false,
    is_skippable: true,
    is_swappable: false,
    max_retries_reached: 0,
    next_charge_scheduled_at: "2021-12-10T00:00:00",
    order_day_of_month: null,
    order_day_of_week: null,
    order_interval_frequency: "3",
    order_interval_unit: "month",
    price: 49.97,
    product_title: "Mouth Strips - Subscription - 3 Pack",
    properties: [
      {
        name: "charge_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_frequency",
        value: 3,
      },
      {
        name: "shipping_interval_unit_type",
        value: "month",
      },
    ],
    quantity: 1,
    recharge_product_id: 2019804,
    shopify_product_id: 6626758230131,
    shopify_variant_id: 39424489521267,
    sku: "S9-1OFP-8SS3",
    sku_override: false,
    status: "ACTIVE",
    updated_at: "2021-08-27T12:32:19",
    variant_title: "",
  },
]

let table = /*html*/ `
<table>
    <thead>
        <tr>
            <td>№</td>
            <th>Customer</th>
            <th>Subscription Date</th>
            <th>Date of FIRST charge</th>
            <th>Date of NEXT charge</th>
            <th>Price</th>
            <th>Charged</th>
            <th>Not charged</th>
            <th>Expired</th>
            <th>Cancelled</th>
            <th>Active</th>
        </tr>
    </thead>
</table>
`

document.body.insertAdjacentHTML("afterbegin", table)

getDataTable(a)

function getDataTable(a) {
  a.map((el, i) => {
    const { email, created_at, next_charge_scheduled_at, price, has_queued_charges, status } = el

    let number = i + 1

    let hasQueuedCharges = 0
    let hasNotQueuedCharges = 0
    let statusActive = "-"
    let statusCancelled = "-"
    let statusExpired = "-"
    let nextCharge = "-"

    if (next_charge_scheduled_at !== null) {
      nextCharge = new Date(next_charge_scheduled_at).toLocaleDateString()
    }
    if (has_queued_charges === 1) {
      hasQueuedCharges = 1
    } else {
      hasNotQueuedCharges = 1
    }

    if (status === "ACTIVE") {
      statusActive = status
    } else if (status === "CANCELLED") {
      statusCancelled = status
    } else {
      statusExpired = status
    }

    document.querySelector("table").insertAdjacentHTML(
      "beforeend",
      `<tbody><tr>
        <td>${number}</td>
        <th>${email}</th>
        <th>${new Date(created_at).toLocaleDateString()}</th>
        <th>${new Date(new Date(created_at).setDate(new Date(created_at).getDate() + 14)).toLocaleDateString()}</th>
        <th>${nextCharge}</th>
        <th>${price}</th>
        <th>${hasQueuedCharges}</th>
        <th>${hasNotQueuedCharges}</th>
        <th>${statusExpired}</th>
        <th>${statusCancelled}</th>
        <th>${statusActive}</th>
      </tr></tbody>`
    )
  })
}

// function getFetchData() {
//   fetch("https://api.rechargeapps.com/subscriptions?created_at_min=2021-08-25&shopify_variant_id=39424489521267", {
//     headers: {
//       "X-Recharge-Access-Token": "3693bbb190af74174e250a9c456a08bfe8035d1bd27f391b0144481e",
//     },
//   })
//     .then((response) => {
//       return response.json()
//     })
//     .then((store) => {
//       console.log(store)
//     })
//     .catch((error) => {
//       console.error(error)
//     })
// }
// getFetchData()
